### ISSUE TITLE
Can't initialize BpmnModeler when deploying Vue project on Tomcat

### ISSUE THREAD

**Issue by NamTang** [bpmn-io/bpmn-js-embedded-comments#5]
__Describe the Bug__
Everything is ok when I'm running my project with `npm run serve` but when I build the project with `npm run build` and deploy it on Tomcat9 it seems like the `bpmnjs = new BpmnModeler({...}) is not working.` Its run normally when I remove the `EmbeddedComments` component.

__Steps to Reproduce__

1.   npm install --save bpmn-js-embedded-comments
2. 
```
mounted() {
var bpmnjs  = new BpmnModeler({
 ...
      additionalModules: [
        ....
        EmbeddedComments,
      ],
...
});
}
```
3. npm run build
4. copy `dist` to Tomcat9 and start the server.
5. now this happens: `bpmnjs = null;`
Diagram.js:56 Failed to instantiate component
(anonymous) @ Diagram.js:56
Diagram.js:57 Error: No provider for "e"! (Resolving: comments -> e)
    at a (index.esm.js:110)
    at Object.get (index.esm.js:96)
    at e (index.esm.js:150)
    at index.esm.js:169
    at Array.map (<anonymous>)
    at c (index.esm.js:165)
    at Array.u (index.esm.js:180)
    at ue.e [as get] (index.esm.js:144)
    at Diagram.js:54
    at Array.forEach (<anonymous>)
(anonymous) @ Diagram.js:57
vue.runtime.esm.js:1888 Error: No provider for "e"! (Resolving: comments -> e)
    at a (index.esm.js:110)
    at Object.get (index.esm.js:96)
    at e (index.esm.js:150)
    at index.esm.js:169
    at Array.map (<anonymous>)
    at c (index.esm.js:165)
    at Array.u (index.esm.js:180)
    at ue.e [as get] (index.esm.js:144)
    at Diagram.js:54
    at Array.forEach (<anonymous>)
re @ vue.runtime.esm.js:1888
edit:1 Failed to load resource: the server responded with a status of 404 ()

__Expected Behavior__
run the same as the bpmnjs commenting example.

__Environment__
- OS: [e.g. Windows 10]
- Tomcat: 9.0.24
- Vuejs: 2

**Comment by nikku** [comment]
Does it work fine without Vue and Tomcat, i.e. when you create a JS only setup of bpmn-js + embedded comments?

**Comment by NamTang** [comment]
yes, it does work fine with js only setup

**Comment by nikku** [comment]
I guess this is an issue with minification hints missing from the library which I've added via https://github.com/bpmn-io/bpmn-js-embedded-comments/commit/897cbc2a917563620314760a5981c111a8386166.

Please double check, if you can install and consume the library from `github:bpmn-io/bpmn-js-embedded-comments#master`.

**Comment by NamTang** [comment]
> I guess this is an issue with minification hints missing from the library which I've added via [897cbc2](https://github.com/bpmn-io/bpmn-js-embedded-comments/commit/897cbc2a917563620314760a5981c111a8386166).
> 
> Please double check, if you can install and consume the library from `github:bpmn-io/bpmn-js-embedded-comments#master`.

I have successfully run the project with your suggestion, thank you very much, really appreciated.

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-embedded-comments/commit/897cbc2a917563620314760a5981c111a8386166 it seems.
