### ISSUE TITLE
Do not show delete comments in bpmn-js-embedded-comments.

### ISSUE THREAD

**Issue by nnthanhhuy** [bpmn-io/bpmn-js-embedded-comments#6]
__Describe the Bug__

Do not show delete comments in bpmn-js-embedded-comments.

__Steps to Reproduce__

1. npm install --save bpmn-js-embedded-comments
2. 
![Screenshot (1)](https://user-images.githubusercontent.com/71427779/97385872-3c2c5000-1905-11eb-98c0-10cbe436696b.png)

3. npm run dev
4. When I hover over it, it does not show delete
![Screenshot (2)](https://user-images.githubusercontent.com/71427779/97386258-05a30500-1906-11eb-9786-bac944a1fa75.png)

5. When I go to node_modules / bpmn-js-embed-comment / dist / index.esm.js directory find line 168
![Screenshot (3)](https://user-images.githubusercontent.com/71427779/97386827-4ea78900-1907-11eb-8335-cb58d9a3e797.png)
replace into
![Screenshot (4)](https://user-images.githubusercontent.com/71427779/97387216-2cfad180-1908-11eb-8cdf-2b767d775685.png)
then it works
![Screenshot (5)](https://user-images.githubusercontent.com/71427779/97387559-d0e47d00-1908-11eb-9429-9ce0fb967b8e.png)

__Expected Behavior__

Can you help me find another solution without fixing the source code?

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 10]
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment]
Thanks for reporting! It seems the delete-node simply got erased because of malformed HTML

https://github.com/bpmn-io/bpmn-js-embedded-comments/blob/66b1dae940945fa0243e1023ad034372dc9acf72/lib/comments.js#L146

I think there is currently no workaround instead of simply fixing it. You already suggested a fix, mind you creating a PR for it?

**Comment by nnthanhhuy** [comment]
Thanks for the feedback! I created a PR looking forward to receiving feedback.
