### ISSUE TITLE
Allow other languages besides English

### ISSUE THREAD

**Issue by alexandru-drincianu** [bpmn-io/bpmn-js-embedded-comments#8]
It seems that currently the package does not support translations. Is there any chance to have the possibility to customize the messages shown to the user (e.g.: "Add a comment")?

**Comment by nikku** [comment]
(1) Please use our existing issue templates when creating a new issue
(2) There surely exists the option to enhance this library. Contributions welcome!

----

If you plan to contribute ensure you follow along our existing [i18n example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/i18n#usage-summary) and use the [`translate`](https://github.com/bpmn-io/diagram-js/blob/develop/lib/i18n/translate/translate.js) service to translate UI elements.

**Comment by nikku** [comment]
We'll not follow-up on this at this time. Happy to take a contribution to add internationalization to this extension though!

**Comment by alexandru-drincianu** [comment]
Hi @nikku, I have checked multiple modules/extensions for the bpmn library (i.e Minimap, Properties pannel, Linting etc.) and I have noticed that there are multiple solutions for implementing Translations:

- const translate = useService('translate');
- var translate = this._injector.get('translate', false) || function(s) { return s; };

Considering that I cannot test the changes locally, can you please guide me towards the proper implementation of Translations so I can add the changes and create a pull request?

Thank you in advance for you response!

**Comment by nikku** [comment]
In core modeling context, please use

```
ar translate = this._injector.get('translate', false) || function(s) { return s; };
```

In JSX / preact scopes, please use 

```
const translate = useService('translate');
```

In particular this library shall use the standard `translate` service, in the [core modeling way](https://github.com/bpmn-io/bpmn-js/search?p=2&q=translate).
